### ISSUE TITLE
IRI  > getIRI()

### ISSUE THREAD

**Issue by GCHQDeveloper42** [gchq/HQDM#10]
`IRI.java` defines a string `iri` which can be set independently of the `base` namespace and resource name (`value`). This mean the URI returned by the `getIri()` method could be different from the set value of the `IRI`.

the property `iri` and its corresponding getter/setter methods should be removed and replaced with a `getUri()` method which returns a URI that is constructed from the base and value properties of that object. This will ensure the returned URI will always correspond to the set properties of the instance of IRI.

**Comment by twalmsley** [comment]
`IRI` and other RDF-specific code will be moved to a new repo, so this issue should be recreated there when it is ready and this one can then be closed.

**Comment by twalmsley** [comment]
Looking at the code for `IRI` it seems that the `base` field is never used so it can be removed.

Also, the `setters` are never used so can also be removed, which resolves this problem and makes the `IRI` immutable, and is also a good idea.

The `resource` and `iri` fields are used fairly extensively on their own, so they should be retained for efficiency to remove the overhead of parsing the `iri` or the proposed `URL`. 

The `URL` class can be used to validate the String `iri` before parsing out the `resource` value.

The new `HQDM-IRI` repo will have these fixes along with a unit test, so this issue can be closed.
