### ISSUE TITLE
Please create a release for version 1.0

### ISSUE THREAD

**Issue by tomkoukoulis** [gchq/HQDM#29]
Could you please create a release for version 1.0 and ideally put it on maven central as it is breaking builds not having a 1.0 release. Thank you.

**Comment by GCHQDeveloper42** [comment]
Hi @tomkoukoulis, 
I'm afraid this repository is being discontinued now that the HQDM object library has been migrated to a sub-module of [Magma Core](https://github.com/gchq/MagmaCore). As such we are not planning to release this repository to Maven Central separately as doing so could create future complications with multiple variants of HQDM library.

We are planning to release Magma Core on Maven Central in the near future. But for now you may continue using the latest version of HQDM (`1.1-SNAPSHOT`), available here, as a stepping-stone to using the [Magma Core HQDM sub-module](https://github.com/gchq/MagmaCore/tree/develop/hqdm), which is currently up-to-date with this version of HQDM. Magma Core v1.1.0 will be officially released and hosted on Maven Central soon.
