### ISSUE TITLE
Remove underscores from attribute setters in builder classes.

### ISSUE THREAD

**Issue by GCHQDeveloper42** [gchq/HQDM#5]
HQDM was originally written in the EXPRESS data modelling language, which uses 'snake case' for defining entity/relationship names. This was retained during the conversion from EXPRESS to the Java object models in order to preserve the distinction between relationship type where underscores denote the type of relationship being invoked (e.g. `member_of`, `member_of_` & `member__of`), but also incorporated Java's camel case naming convention for method names resulting in a combination of snake and camel case method names for attribute setters in the builder objects which does not fit any convention.

Given Java's polymorphism, It would be possible to remove the underscores from method names entirely, as the parameter type would be enough to determine the association type and method being invoked. This would resolve to use Java's camel case method names convention and should not break consistency with the EXPRESS notation, as the relationship type and entity class names are still defined appropriately for Linked Data by `iri/HQDM.java`.

Due to HQDM's inheritance model, care must be taken to insure that Java's polymorphism does not break in cases where relationship sub-types apply equally to entities with a supertype

 (e.g. `Activity` has the `part__of` relationship to a `SpatioTemporalExtent` and a `part_of` relationship to an `Activity`, which is itself ultimately a sub-type of `SpatioTemporalExtent`. Therefore it may be possible to inadvertently apply the wrong relationship type to a property, or prevent certain relationships to entities being applied (e.g. a `part__of` relationship to another `Activity` because it would instead invoke the `part_of` relationship).

To resolve this, sub-type relationships could be given more fitting names that describe the nature of the relationship they represent (e.g. instead of `part_of_` could be changed to `partOfAgreementExecution`). This would make the distinction between relationships more explicit, as the possibility of invoking the wrong attribute setter through inheritance is no longer a concern. As this would only appear in the object Builder method names, it would not have any bearing on the resulting Java or Linked Data objects, so consistency with the original HQDM would be maintained. 

## Mandatory Properties
There is also the matter of `_M` which appears as a suffix to some entity relationships when the relationship is mandatory and is not the inverse of another relationship. This is a historical artifact of the text processing used to convert the EXPRESS to Java, but is more-or-less redundant, so could be removed in conjunction with this change. A note could be added to the method Javadoc to indicate the property is mandatory.

**Comment by twalmsley** [comment]
It could be that the `_M` prefix is there to help code-completion tools make it easier to see which properties a developer must set, rather than guessing or having to check the `Builder.build()` method, javadoc, or getting a runtime error. Its not ideal but it does seem to help productivity a little.

**Comment by twalmsley** [comment]
`Builder` classes have been removed as part of issue #17 so this is no longer a problem. Name variations involving variable combinations of underscores will be avoided in future in favour of more descriptive method names in cases where there would otherwise be a name clash.
